#ifndef BUSE_CONFIG
#define BUSE_CONFIG

#include <linux/blkdev.h>

#define BUSE_MAX_SEGMENT_SIZE PAGE_SIZE
#define BUSE_MAX_SEGMENTS 32
#define BUSE_MAX_SIZE_PER_COMMAND (BUSE_MAX_SEGMENT_SIZE * BUSE_MAX_SEGMENTS)
#define BUSE_PTES_PER_COMMAND (BUSE_MAX_SIZE_PER_COMMAND / PAGE_SIZE)
#define BUSE_MAX_ZONE_SECTORS ((1 * 1024 * 1024 * 1024) >> SECTOR_SHIFT)

#define BUSE_MAX_ZONES (128 * 1024)

#endif
