#ifndef BUSE_CONFIG
#define BUSE_CONFIG

#ifdef __KERNEL__
#include <linux/blkdev.h>
#endif

#define BUSE_MAX_SEGMENTS 256
#define BUSE_MAX_SIZE_PER_COMMAND (128 * 1024 * 1024)
#define BUSE_PTES_PER_COMMAND (BUSE_MAX_SIZE_PER_COMMAND / PAGE_SIZE)
#define BUSE_MAX_ZONE_SECTORS ((1 * 1024 * 1024 * 1024) >> SECTOR_SHIFT)

#define BUSE_MAX_ZONES (128 * 1024)

#define BUSE_MAP_DATA_THRESHOLD (128 * 1024)

#endif
