#ifndef BUSE_CONFIG
#define BUSE_CONFIG

#define BUSE_MAX_SEGMENT_SIZE PAGE_SIZE
#define BUSE_MAX_SEGMENTS 32
#define BUSE_MAX_SIZE_PER_COMMAND (BUSE_MAX_SEGMENT_SIZE * BUSE_MAX_SEGMENTS)
#define BUSE_PTES_PER_COMMAND (BUSE_MAX_SIZE_PER_COMMAND / PAGE_SIZE)

#endif
